In [1]:
import os
import math
import numpy as np
import time 

#  Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

## Progress bar
from tqdm.notebook import tqdm

# The Basics of PyTorch

In [2]:
import torch
print("Using torch", torch.__version__)

Using torch 1.8.1+cu111


a very good practice is to sutup yor code to be reproducible with the exact same random numbers

In [3]:
torch.manual_seed(42) # Setting the seed

# Tensors

## Initializetion

In [4]:
x = torch.Tensor(2, 3, 4)
print(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


torch.zeros: Creates a tensor filled with zeros

torch.ones: Creates a tensor filled with ones

torch.rand: Creates a tensor with random values uniformly sampled between 0 and 1

torch.randn: Creates a tensor with random values sampled from a normal distribution with mean 0 and variance 1

torch.arange: Creates a tensor containing the values N,N+1,N+2,...,M

torch.Tensor (input list): Creates a tensor from the list elements you provide

In [5]:
# Create a tensor from a (nested) list
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [7]:
# Create a tensor with random values between 0 and 1 with the shape [2, 3, 4]
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


In [6]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor to Numpy, and Numpy to Tensor