![alt text](../metadata/Snipaste_2021-05-24_19-54-36.png "png")

In [1]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)

![alt text](../metadata/Snipaste_2021-05-24_19-56-18.png "png")

In [2]:
edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)

In [3]:
edge_index.shape

torch.Size([4, 2])

In [4]:
edge_index.t()

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])

In [5]:
edge_index.t().contiguous()

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])

In [6]:
data.keys

['x', 'edge_index']

In [7]:
data['x']

tensor([[-1.],
        [ 0.],
        [ 1.]])

In [8]:
'edge_attr' in data

False

In [9]:
data.num_edges

4

In [10]:
data.num_nodes

3

In [11]:
data.num_node_features

1

In [12]:
data.num_edge_features

0

In [13]:
data.contains_isolated_nodes()

False

In [14]:
data.contains_self_loops()

False

In [15]:
data.is_directed()

False

In [16]:
# Transfer data object to GPU.
device = torch.device('cuda')
data = data.to(device)

device(type='cuda')

In [18]:
from torch_geometric.datasets import TUDataset

dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES')

Extracting /tmp/ENZYMES/ENZYMES/ENZYMES.zip
Processing...
Done!


In [19]:
len(dataset)

600

In [20]:
dataset.num_classes

6

In [21]:
dataset.num_node_features

3